apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-argo-cd
  name: grafana-argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-argo-cd
    spec:
      containers:
      - image: grafana/grafana:latest
        imagePullPolicy: Always
        name: grafana-argo-cd
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always