apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserviceone
  labels:
    app: microserviceone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserviceone
  template:
    metadata:
      labels:
        app: microserviceone
    spec:
      containers:
      - name: microserviceone
        image: vismarkjuarez1994/microserviceone
        ports:
        - containerPort: 2019
        env:
          - name: FIRST_NAME
            value: Mr.Kubernetes
          - name: AGE
            value: "100"
