kind: Service
apiVersion: v1
metadata:
  name: microserviceone-service
spec:
  ports:
    - port: 30008 # The port on the Service to expose
      targetPort: 2019 # The port on the destination pod to bind to
      nodePort: 30008 # The port the Service will listen to at the Node level
      protocol: TCP 
  selector:
    app: microserviceone # As specified on the pod-definition
  type: NodePort # The type of Service this service is (as opposed to ClusterIP, Load Balancer, etc)